// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTGDG5Wb2_xHsVPos6x91asaI4-NcCDSM',
    appId: '1:740228806876:web:0bbd9582dc19bf57d1dc19',
    messagingSenderId: '740228806876',
    projectId: 'todoska-2023',
    authDomain: 'todoska-2023.firebaseapp.com',
    storageBucket: 'todoska-2023.appspot.com',
    measurementId: 'G-MFK72F07JR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiSl_a6B20QpGhTwi9gaNFv87Z14UN_I0',
    appId: '1:740228806876:android:dcab5951faee3f97d1dc19',
    messagingSenderId: '740228806876',
    projectId: 'todoska-2023',
    storageBucket: 'todoska-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPdnfLJ7uD6J4CUusRaBEchGQsuQxFsd8',
    appId: '1:740228806876:ios:513ade070617fd4ad1dc19',
    messagingSenderId: '740228806876',
    projectId: 'todoska-2023',
    storageBucket: 'todoska-2023.appspot.com',
    iosClientId: '740228806876-v9apeqhfmf0vne4uep4rhl9f1m06806v.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoska',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPdnfLJ7uD6J4CUusRaBEchGQsuQxFsd8',
    appId: '1:740228806876:ios:513ade070617fd4ad1dc19',
    messagingSenderId: '740228806876',
    projectId: 'todoska-2023',
    storageBucket: 'todoska-2023.appspot.com',
    iosClientId: '740228806876-v9apeqhfmf0vne4uep4rhl9f1m06806v.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoska',
  );
}
